### ISSUE TITLE
Power usage...

### ISSUE THREAD

**Issue by dothebart** [OpenAirCgn/firmware#1]
Its currently permanently pulling 150 mA; removing the sensor then there is about 90 mA;
It seems that after transmitting one should also call:  

    WiFi.maxLowPowerMode(); // go into power save mode

**Comment by a2800276** [comment]
Thanks! I'm currently rewriting most of the firmware anyway and wanted to play around with this anyway. Unfortunately, as long as we're using Arduino, we can't really save a lot of power anyway because of `loop()`

**Comment by erniberni** [comment]
We can do a lot, I think, it doesn't really depend on loop() and Arduino IDE. Look here
[https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/power-management](url)

**Comment by marcel12bell** [comment]
@dothebart ist jetzt drin...
