### ISSUE TITLE
Ping fails for current API Server

### ISSUE THREAD

**Issue by noerw** [OpenAirCgn/firmware#3]
My current router (easybox 803a) does not allow outgoing pings to dot-zero IPs, as a legacy DoS protection [0][1][2]. The actual http connection works however.

(http://influx.datacolonia.de/ resolves to 138.201.88.0)

As the http call is not performed if the ping fails, I can't upload any data to the API.
I'd suggest to skip the ping test, as the http call should fail gracefully anyway..?

[0] http://serverfault.com/questions/10985/is-x-y-z-0-a-valid-ip-address
[1] https://en.wikipedia.org/wiki/IPv4#Addresses_ending_in_0_or_255
[2] https://tools.ietf.org/html/rfc2644

**Comment by marcel12bell** [comment]
@noerw Thanks for the hint! FW update is on the way...
