### ISSUE TITLE
char board, api_key - wrong size 

### ISSUE THREAD

**Issue by erniberni** [OpenAirCgn/firmware#4]
Because I had problems with periodically watchdog reboots I analysed
```
char board[3];
char api_key[6];

```
and this is filled by subroutines
```
char* get_board() {
  byte mac[6];
  WiFi.macAddress(mac);
  sprintf(board, "%02X%02X%02X", mac[2], mac[1], mac[0]);
  return board;
}

char* get_api_key() {
  byte mac[6];
  WiFi.macAddress(mac);
  sprintf(api_key, "%02X%02X%02X%02X%02X%02X", mac[5], mac[4], mac[3], mac[2], mac[1], mac[0]);
  return api_key;
}

```
As this is filled with characters it will need 12 characters for "api_key" and 6 characters for "board".

Am I wrong ?
Reinhard

**Comment by a2800276** [comment]
nope, completely correct...
my rewrite is taking a little longer than I hoped, but I'll put the current state in a repo this weekend.
